name: thunder_encryption
description: A library for encryption utilities in Dart.
version: 1.0.0
repository: https://github.com/AbdAlftahSalem/encryption

environment:
  sdk: ^3.6.0

dependencies:
#  path:
# Add your dependencies here if needed, e.g., path: ^1.8.0.

dev_dependencies:
  lints: 5.1.0
  test: ^1.24.0
